"""
Synthetic Sample Data Generator
Generates realistic-looking buckets and objects for demo / testing purposes.
All generated resources are tagged so they can be bulk-removed in one click.

Endpoints:
  GET  /api/admin/seeddata/presets          — return available bucket/file presets
  POST /api/admin/seeddata/generate         — create buckets + upload sample objects
  POST /api/admin/seeddata/cleanup          — delete all generated buckets/objects
  GET  /api/admin/seeddata/status           — list what has been generated for a tenant
"""
import io
import json
import time
from typing import List, Optional
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from app.config import get_s3_client
from botocore.exceptions import ClientError

router = APIRouter()

# ── Sample file content generators ───────────────────────────────────────────

def _txt(name: str, topic: str) -> bytes:
    return f"""DDN Infinia — Sample File
========================
File   : {name}
Topic  : {topic}
Created: Demo Load Generator
Note   : This is a synthetic test file generated for demonstration purposes.

{topic} Summary
{'=' * (len(topic) + 8)}
This document contains placeholder content representing a real {topic} file
that would exist in a production Infinia deployment. It demonstrates that
Infinia correctly stores, retrieves, and isolates objects across tenants.

Sections:
  1. Overview       — Describes the {topic} context
  2. Configuration  — Relevant parameters and settings
  3. Results        — Output data and metrics
  4. Appendix       — Supporting reference material

[END OF SYNTHETIC SAMPLE FILE]
""".encode()


def _pdf(title: str) -> bytes:
    """Generate a minimal valid single-page PDF with title text."""
    page_content = f"BT /F1 14 Tf 72 720 Td ({title}) Tj 72 700 Td (DDN Infinia - Sample PDF Document) Tj 72 680 Td (Generated by Infinia Platform Console Load Generator) Tj ET"
    content_len = len(page_content)
    pdf = f"""%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj
4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
5 0 obj<</Length {content_len}>>
stream
{page_content}
endstream
endobj
xref
0 6
0000000000 65535 f
trailer<</Size 6/Root 1 0 R>>
startxref
0
%%EOF"""
    return pdf.encode()


def _docx_stub(title: str) -> bytes:
    """Return a plaintext stub with .docx extension — enough to show in object list."""
    return f"""[Microsoft Word Document - Sample]
Title: {title}
Generator: DDN Infinia Platform Console

This is a synthetic Word document stub generated for demo purposes.
In a real deployment this would be a binary OOXML/ZIP-format .docx file.

Content Outline:
  - Executive Summary
  - Technical Architecture
  - Implementation Plan
  - Risk Assessment
  - Sign-off

[END STUB]
""".encode()


def _csv(name: str) -> bytes:
    rows = ["timestamp,tenant,bucket,operation,bytes,latency_ms,status"]
    import random, datetime
    base = datetime.datetime(2026, 9, 1, 0, 0, 0)
    for i in range(50):
        ts  = (base + datetime.timedelta(hours=i*3)).isoformat()
        ops = random.choice(["PutObject","GetObject","DeleteObject","ListObjects"])
        byt = random.randint(1024, 10_485_760)
        lat = random.randint(2, 250)
        sta = random.choice(["200","200","200","403","404"])
        rows.append(f"{ts},{name},{name}-bucket,{ops},{byt},{lat},{sta}")
    return "\n".join(rows).encode()


# ── Preset bucket/object definitions ─────────────────────────────────────────

BUCKET_PRESETS = [
    {
        "id":          "docs-archive",
        "bucket":      "docs-archive",
        "description": "Document Archive — legal, HR, and compliance documents",
        "objects": [
            ("quarterly-report-q3-2026.pdf",    "pdf"),
            ("employee-handbook-v3.pdf",          "pdf"),
            ("project-proposal-infinia.docx",     "docx"),
            ("meeting-notes-sept.txt",            "txt"),
            ("sla-agreement-ncp.pdf",             "pdf"),
            ("vendor-contract-2026.docx",         "docx"),
        ]
    },
    {
        "id":          "media-assets",
        "bucket":      "media-assets",
        "description": "Media & Marketing — datasheets, briefs, brand assets",
        "objects": [
            ("product-datasheet-infinia.pdf",     "pdf"),
            ("design-brief-q4.docx",              "docx"),
            ("campaign-notes-oct.txt",            "txt"),
            ("brand-guidelines-2026.pdf",         "pdf"),
            ("press-release-draft.docx",          "docx"),
        ]
    },
    {
        "id":          "data-lake-raw",
        "bucket":      "data-lake-raw",
        "description": "Raw Data Lake — telemetry, logs, ingestion manifests",
        "objects": [
            ("telemetry-log-2026-09.txt",         "txt"),
            ("sensor-readings-cluster1.csv",      "csv"),
            ("ingestion-manifest.txt",            "txt"),
            ("pipeline-config.txt",              "txt"),
            ("anomaly-report-sept.txt",           "txt"),
        ]
    },
    {
        "id":          "compliance-vault",
        "bucket":      "compliance-vault",
        "description": "Compliance Vault — audit trails, GDPR, incident reports",
        "objects": [
            ("audit-trail-2026.pdf",              "pdf"),
            ("gdpr-compliance-report-q3.pdf",     "pdf"),
            ("data-retention-policy.docx",        "docx"),
            ("incident-report-001.txt",           "txt"),
            ("penetration-test-summary.pdf",      "pdf"),
        ]
    },
]

GENERATOR_TAG_KEY   = "x-amz-meta-generated-by"
GENERATOR_TAG_VALUE = "infinia-load-generator"


def _make_content(fname: str, ftype: str) -> tuple:
    """Return (bytes, content_type) for a given file."""
    stem = fname.replace("-", " ").replace("_", " ").title()
    if ftype == "pdf":
        return _pdf(stem), "application/pdf"
    elif ftype == "docx":
        return _docx_stub(stem), "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    elif ftype == "csv":
        return _csv(stem), "text/csv"
    else:
        return _txt(fname, stem), "text/plain"


# ── API endpoints ─────────────────────────────────────────────────────────────

@router.get("/seeddata/presets")
def get_presets():
    return {"presets": [
        {"id": p["id"], "bucket": p["bucket"], "description": p["description"],
         "object_count": len(p["objects"])}
        for p in BUCKET_PRESETS
    ]}


class GenerateRequest(BaseModel):
    tenant:     str
    preset_ids: List[str]   # which bucket presets to create; empty = all


class CleanupRequest(BaseModel):
    tenant:  str
    buckets: List[str]      # bucket names to delete


@router.post("/seeddata/generate")
def generate_sample_data(req: GenerateRequest):
    """Create selected buckets and upload sample objects. Streams SSE progress."""

    selected = [p for p in BUCKET_PRESETS if not req.preset_ids or p["id"] in req.preset_ids]

    def _sse(step, status, message, **extra):
        """Build an SSE data line without backslashes inside f-strings."""
        payload = {"step": step, "status": status, "message": message}
        payload.update(extra)
        return "data: " + json.dumps(payload) + "\n\n"

    def _stream():
        s3 = get_s3_client(req.tenant)
        created_buckets = []
        total_objects   = 0
        total_errors    = 0

        init_msg = "Starting load generator for tenant " + req.tenant + " — " + str(len(selected)) + " bucket(s) to create"
        yield _sse("init", "running", init_msg)
        time.sleep(0.3)

        for preset in selected:
            bname = preset["bucket"]

            # Create bucket
            yield _sse("bucket", "running", "Creating bucket " + bname + "…")
            try:
                try:
                    s3.create_bucket(Bucket=bname)
                except ClientError as e:
                    if e.response['Error']['Code'] in ('BucketAlreadyExists', 'BucketAlreadyOwnedByYou'):
                        pass  # already exists — still upload objects
                    else:
                        raise
                created_buckets.append(bname)
                yield _sse("bucket", "success", "Bucket " + bname + " ready")
            except Exception as e:
                yield _sse("bucket", "failed", "Bucket " + bname + " failed: " + str(e))
                total_errors += 1
                continue

            # Upload objects
            for fname, ftype in preset["objects"]:
                yield _sse("upload", "running", "  Uploading " + fname + "…")
                try:
                    content, ctype = _make_content(fname, ftype)
                    s3.put_object(
                        Bucket=bname,
                        Key=fname,
                        Body=io.BytesIO(content),
                        ContentType=ctype,
                        Metadata={GENERATOR_TAG_KEY: GENERATOR_TAG_VALUE},
                    )
                    total_objects += 1
                    size_kb = round(len(content) / 1024, 1)
                    ext = ctype.split("/")[1] if "/" in ctype else ctype
                    yield _sse("upload", "success", "  " + fname + " (" + str(size_kb) + " KB, " + ext + ")")
                except Exception as e:
                    yield _sse("upload", "failed", "  " + fname + " failed: " + str(e))
                    total_errors += 1
                time.sleep(0.1)

        summary = "Done — " + str(len(created_buckets)) + " bucket(s), " + str(total_objects) + " objects uploaded"
        if total_errors:
            summary += ", " + str(total_errors) + " error(s)"
        final_status = "success" if not total_errors else "warning"
        yield _sse("done", final_status, summary, buckets=created_buckets, object_count=total_objects)

    return StreamingResponse(_stream(), media_type="text/event-stream",
                             headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@router.post("/seeddata/cleanup")
def cleanup_sample_data(req: CleanupRequest):
    """Delete all objects and buckets that were created by the load generator."""
    s3 = get_s3_client(req.tenant)
    results = []

    for bname in req.buckets:
        bucket_result = {"bucket": bname, "objects_deleted": 0, "error": None}
        try:
            # List and delete all objects first
            paginator = s3.get_paginator("list_objects_v2")
            for page in paginator.paginate(Bucket=bname):
                objects = [{"Key": o["Key"]} for o in page.get("Contents", [])]
                if objects:
                    s3.delete_objects(Bucket=bname, Delete={"Objects": objects})
                    bucket_result["objects_deleted"] += len(objects)
            # Delete the bucket
            s3.delete_bucket(Bucket=bname)
            bucket_result["status"] = "deleted"
        except ClientError as e:
            bucket_result["status"] = "error"
            bucket_result["error"]  = e.response["Error"]["Code"]
        except Exception as e:
            bucket_result["status"] = "error"
            bucket_result["error"]  = str(e)
        results.append(bucket_result)

    total_deleted = sum(r["objects_deleted"] for r in results)
    errors        = [r for r in results if r["status"] == "error"]
    return {
        "results":       results,
        "buckets_cleaned": len([r for r in results if r["status"] == "deleted"]),
        "objects_deleted": total_deleted,
        "errors":          len(errors),
    }
